version: '3'

services:
  ids_init:
    build: .
    command: python IDS_init.py

  orion_init:
    build: .
    command: python orion_init.py

  quantumleap_init:
    build: .
    command: python quantumleap_init.py

  ids_agent:
    build: .
    command: python IDS_Agent.py
    restart: always

  scheduler:
    build: .
    command: python scheduler.py
    restart: always
